### ISSUE TITLE
daps locdrop/unpack locdrop: manifest files are incorrect

### ISSUE THREAD

**Issue by taroth21** [tomschr/daps#653]
In the doc-slesforsap repo, profiling is used to create both the Quick Start and the Guide from the same set of files. When  doing a locdrop, we need to use separate target directories for both guides, otherwise files are overwritten.

What is more: the file list created in the manifest files is not correct, neither for the setfiles nor for the transfiles. 
This leads to problems when trying to unpack the tarballs with `daps unpack-locdrop`, because it unpacks only some of the files, but not all of them.

See https://github.com/SUSE/doc-slesforsap/blob/maintenance/15_SP3/l10n/ja-jp/guide/SLES-SAP-guide_manifest_trans.txt (lists 4 files) and compare to the list of files needed for the SAP Guide in https://github.com/SUSE/doc-slesforsap/tree/maintenance/15_SP3/l10n/ja-jp/guide/xml (31 files) and the https://github.com/SUSE/doc-slesforsap/tree/maintenance/15_SP3/l10n/ja-jp/guide/images/src. (We had to copy the remaining files from the tarball to GH manually).

For the SAP Guide, the file xml/s4s_components_quick.xml is correctly listed in the `notrans` manifest file. For the SAP Quick Start however, the file does not show up in any of the two manifest files, but is at least correctly located in the `trans` tarball.

**Comment by fsundermeyer** [comment]
Can't be repoduced anymore, closing as invalid.
