### ISSUE TITLE
Get rid of `_color` in PDF file names

### ISSUE THREAD

**Issue by ghost** [tomschr/daps#655]
### Problem description

DAPS-generated PDFs still include the word `_color` in each file name. At this point, that's mostly a historical artifact which stems from the time when grayscale output was still the default. Given that these file names are the same names that we use when we publish stuff on dsc, it would be good to have a cleaner/shorter file name.

### Expected behavior

Remove `_color` from file names of colored PDFs. For differentiation of grayscale PDFs, you can keep `_gray` in file names of PDF generated with `--grayscale`. (Or we could consider just removing the `--grayscale` parameter altogether.) 

### Steps to reproduce problem

Generate PDF. Look at the file name.
Generate the same PDF but with `--grayscale`. Look at the file name.

**Comment by fsundermeyer** [comment]
Fixed with 2b1ece7
