### ISSUE TITLE
Use ditaa with patch for the --font-family option

### ISSUE THREAD

**Issue by tbazant** [tomschr/daps#657]
Currently, the font family is hard-wired in ditaa. Using custom font family makes it more usable for graphical corporate layout.

The pull request that implements this is https://github.com/stathissideris/ditaa/pull/35

@fsundermeyer @tomschr Can we test the patched one and replace ditaa we have in out doc tools repo with the patched one?

**Comment by ghost** [comment]
1. @janajaeger wants to focus diagramming efforts on SVG input only, I think.
~I am not sure if DITAA should be a priority.~
2. There's also the question of what to do with the request for SVGBob (#636) -- imo it does not make sense to support both DITAA and SVGBob as they are very similar, we really should decide.
3. We currently have v0.10 of DITAA available in the D:T OBS repo only. We should probably try to update to the latest unstable version from the repo first (incidentally that includes SVG export of diagrams too) before trying to apply the patch.
4. It may be a bit of an issue that we would depend on an unstable build of DITAA that includes a new, backward-incompatible command-line switch.

**Comment by janajaeger** [comment]
@sknorr your info is somewhat outdated. We'd love to use ditaa and restrict its use to flowcharts. More advanced stuff should be done with Inkscape.

**Comment by fsundermeyer** [comment]
There does not seem to be any upstream interest in accepting the patch, and I do not think we should create a "SUSE" fork of the ditaa package. Closing
