### ISSUE TITLE
Replace footnoteref to xref (AsciiDoc)

### ISSUE THREAD

**Issue by KucharczykL** [tomschr/daps#700]
## Problem Description

Re-using footnotes with defined ID is not allowed:

```asciidoc
* note1 footnote:reusable[This footnote can be re-used.]
* note2 footnote:reusable[]
```

Results in:

```
Fatal error: The document contains XML errors:
/home/lukas/work/git/release-notes-sles/build/.profiled/noprofile/release-notes.xml:3612:78:
error: element "footnoteref" not allowed here; expected the element end-tag, text or element "alt",
"annotation", "author", "buildtarget", "citetitle", "code", "command", "constant", "date", "editor", "email",
"emphasis", "enumidentifier", "enumname", "enumvalue", "envar", "filename", "firstterm", "footnote",
"foreignphrase", "function", "glossterm", "guimenu", "indexterm", "inlinemediaobject", "jobtitle", "keycap",
"keycombo", "link", "literal", "macroname", "menuchoice", "namespace", "namespacename", "ns:include",
"option", "orgname", "package", "parameter", "person", "personname", "phrase", "productname", "productnumber",
"prompt", "property", "quote", "remark", "replaceable", "revnumber", "subscript", "superscript", "systemitem", "tag",
"templatename", "trademark", "typedefname", "unionname", "uri", "varname" or "xref" (with
xmlns:ns="http://www.w3.org/2001/XInclude") /home/lukas/work/git/release-notes-sles/build/.profiled/noprofile
release-notes.xml:3612:78: error: attribute "linkend" not allowed here
```

## Expected Behaviour

Referring to previously defined footnotes works.

## Additional information

See https://gitlab.suse.de/documentation/release-notes-sles/-/merge_requests/332

**Comment by tomschr** [comment]
I've transferred this issue to daps as this may be implemented in the postprocess stylesheet.

**Comment by KucharczykL** [comment]
After the discussion yesterday, I am not sure this issue is solvable in post-processing.

It seems we would have to duplicate the functionality that DocBook provides for this element: it's easy to replace `footnoteref` with `xref` but this results in the link having no link text (displays `???`). When `footnoteref` is processed by DocBook it is automatically assigned link text based on order in the document, starting from `[a]`, `[b]`, etc.

I think `footnoteref` should be allowed in GeekoDoc because it's essential for working with `footnote` elements that are re-used.

**Comment by tomschr** [comment]
Thanks Lukas for your comments. Ok, some facts first:

The content model for [`<xref/>`](https://tdg.docbook.org/tdg/5.2/xref.html) and [`<footnoteref/>`](https://tdg.docbook.org/tdg/5.2/footnoteref.html) is the same. Both don't allow any child elements. In other words, you can use them interchangeably. It's purely semantic. :wink: 

From a DocBook/schema perspective, I would prefer to focus on `<xref/>`. only. Less elements to worry about. :wink: 

I'd like to comment on some of your remarks:

>  it's easy to replace footnoteref with xref but this results in the link having no link text (displays ???)

If you get ??? as output, then it's a sign that your ID/IDREF connection is broken. This should (and will) lead to validation errors anyway, regardless if you use `<xref/>` or `<footnoteref/>`.

> When footnoteref is processed by DocBook it is automatically assigned link text based on order in the document, starting from [a], [b], etc.

So it will be with `<xref/>`. :slightly_smiling_face: 

All in all, a `<footnoteref/>` is not necessary to work with footnotes at all. You can use also `<xref/>`, it should work as well. If not, then something in the stylesheet is wrong.

Does that make sense? Or do I miss something?

**Comment by KucharczykL** [comment]
Thank you for the explanation, I now understand the situation a bit more!

It would be great if everything just worked with `<xref/>`, I have no special attachment to `<footnoteref/>` :+1:

Can you try making a footnote and reference to it in AsciiDoc and see the result? For me it currently doesn't work as I said because of the missing link text. Maybe I'm missing something? I'm following the docs: https://docs.asciidoctor.org/asciidoc/latest/macros/footnote/

```
Regular text footnote:testid[Footnote text]
More regular text footnote:testid[]
```

Result:
```
Regular text [1] More regular text ???
```

**Comment by tomschr** [comment]
Thanks Lukas for your feedback, much appreciated. :+1: 

After looking a bit closer to this issue, I can confirm it is indeed an issue in the stylesheets. I get the "???" also for the reference to the footnote. This is wrong and shouldn't be the case. Sorry for that!

I've tested it with your example. When I create a reference to a footnote and apply commit 8452faf, I get the correct `<xref/>` but the rendering is wrong, both HTML and PDF. :disappointed: 

From my understanding we have actually two issues here:

1. Renaming `<footnoteref/>` to `<xref/>`. This is covered in commit 8452faf.
2. Render the reference correctly, both in HTML and PDF. This is what we are currently lacking.

So I was right and wrong at the same time by moving this issue here. :laughing: Could you do me a favor and open another issue in the openSUSE/suse-xsl repo and insert a link to this issue?

Many thanks!

**Comment by KucharczykL** [comment]
Opened an issue: https://github.com/openSUSE/suse-xsl/issues/524

**Comment by fsundermeyer** [comment]
Has been fixed upstream (suse-xsl-stylesheets)
