### ISSUE TITLE
Have a check for empty inline elements

### ISSUE THREAD

**Issue by jfaltenbacher** [tomschr/daps#727]
Problem description

When some inline elements are left empty, all text following the empty elements is rendered in monofont for HTML output.

The screen below shows how it looks in the Italian HTML file. The tag is missing in the 'per ulteriori' sentence, but the content was added to the end of the sentence (dhcp.conf is duplicated).

![image](https://github.com/openSUSE/daps/assets/77108806/95a4a3f2-9f6e-44a2-ad16-c0143254911e)

Expected behavior
Check for empty line elements during validation by using this stylesheet: https://github.com/openSUSE/daps/blob/main/contrib/check-source/find-empty-inlines.xsl

**Comment by fsundermeyer** [comment]
Implemented with 18fb41da0384265a5ab320c73ea8e37bf668bb0d
